### ISSUE TITLE
Why are these upper and lower bounds not -inf/inf?

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/DESDEO#136]
https://github.com/industrial-optimization-group/DESDEO/blob/89b778050bbb7d247e898c8f2ca64bc74ca23873/desdeo/tools/scalarization.py#L578

**Comment by juropo** [comment]
I have no idea

**Comment by juropo** [comment]
Looking at the documentation and what it is supposed to do, I'm fairly certain it should be unconstrained.

**Comment by jpajasmaa** [comment]
This same issue is also in

https://github.com/industrial-optimization-group/DESDEO/blob/1b8ffa91a869005633d41bb33840f1e9738d8ab4/desdeo/tools/scalarization.py#L578

and 

https://github.com/industrial-optimization-group/DESDEO/blob/1b8ffa91a869005633d41bb33840f1e9738d8ab4/desdeo/tools/scalarization.py#L933

and

https://github.com/industrial-optimization-group/DESDEO/blob/1b8ffa91a869005633d41bb33840f1e9738d8ab4/desdeo/tools/scalarization.py#L1121

**Comment by juropo** [comment]
Yeah, those seemed to be wrong as well
