### ISSUE TITLE
Pyomo version requirement needs to be upped

### ISSUE THREAD

**Issue by juropo** [industrial-optimization-group/DESDEO#191]
Pyomo <6.7.4 is not compatible with numpy 2.0

**Comment by gialmisi** [comment]
Indeed. When installing deps with Poetry, pyomo version 6.0 and up is required. Poetry resolved the correct version to be >6.7.4 currently (to 6.8.0), so this issue will not usually arise. However, it does not hurt to be explicit with dependencies.

Addresses in commit dea7014

Feel free to reopen this if there are additional issues with pyomo.

**Comment by juropo** [comment]
It came up in practice last night on my home computer. I have no idea how that happened but it was annoying.
