### ISSUE TITLE
Number of objective can be undefuned

### ISSUE THREAD

**Issue by podkop** [industrial-optimization-group/DESDEO#39]
https://github.com/industrial-optimization-group/DESDEO/blob/0c3be0862147d69e5b5485541564b4941a28ff35/desdeo/problem/Problem.py#L111

Why not setting number of objectives explicitly?
Existing of nadir is very method-specific, no need to rely on it.
Even the ideal point is not always needed to be estimated.
Nr. of objectives is a fundamental property, why not setting it explicitly?

**Comment by gialmisi** [comment]
I propose something like this. The assertions have been moved to the constructor. I'm also assuming that the nadir and ideal points have as many elements as the problem has objectives, which is a fair statement in my opinion.

https://github.com/gialmisi/DESDEO/commit/11027443b1c5570a09e425911368a8b903057f7b#diff-7dd9d5c4f9af2057286105dae570853f
