### ISSUE TITLE
[IDEA] Should we continue with Flask with the new webAPI?

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/DESDEO#71]
* **What is the current behavior?**
Currently uses Flask.

* **Describe the solution you'd like**
Is it better/easier to use alternatives such as django/fastapi?

* **What is the motivation/use case for changing the behavior?**
Giovanni, can you comment on the usability, verbosity, and features of django? Fastapi is generally thought to be less verbose. It auto-generates the API docs, and handles request validation/JSON-python conversion automatically. We can use dataclasses/Pydantic for structuring the requests.

* **Describe alternatives you've considered**
Flask, Django, Fastapi

**Comment by jpajasmaa** [comment]
While I don't have extensive experience or knowledge of Django, I have used it enough to know that it has certain way of handling things. And doing this not the Django -way may be hard or not possible. But I don't know does this matter to us, as said I don't have much experience using it.

**Comment by light-weaver** [comment]
Based on the discussion during the technical meeting, we are continuing with Flask.
