### ISSUE TITLE
Add CPU-based rules for dependency choice

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/DESDEO#75]
https://github.com/industrial-optimization-group/DESDEO/blob/9d03e5d736588a21603b683d4a545ca33fd9e2ad/pyproject.toml#L13C28-L13C28

The `polars` python package should probably be the default version that we use. There is probably a way to specify alternative dependencies based on CPU type. I will look into this if this is unresolved by the time I come back.

**Comment by light-weaver** [comment]
Added some ruff rules in as well

**Comment by gialmisi** [comment]
The current solutions seems to work for me at least.
