### ISSUE TITLE
Implementation of a new method: the reference point method

### ISSUE THREAD

**Issue by gialmisi** [industrial-optimization-group/DESDEO#93]
The reference point method described [in this article](https://doi.org/10.1016/0270-0255(82)90038-0) needs to be implemented. The scalarization functions needed [have already been implemented](https://github.com/industrial-optimization-group/DESDEO/blob/desdeo2/desdeo/tools/scalarization.py). A function that computes k+1 solution candidates based on a given reference point needs to be implemented after which the method can be considered to be available in DESDEO. This function should be in a file found in the [desdeo-mcdm package](https://github.com/industrial-optimization-group/DESDEO/tree/desdeo2/desdeo/mcdm). A good example can be found in the [current NIMBUS implementation](https://github.com/industrial-optimization-group/DESDEO/blob/desdeo2/desdeo/mcdm/nimbus.py) on how the file with the reference point method could be structured. The implementation should be documented and tested.

**This issue is related to the re-structuring of DESDEO, see the [branch desdeo2](https://github.com/industrial-optimization-group/DESDEO/tree/desdeo2).**

**Comment by gialmisi** [comment]
@Matskuu I believe you had implemented this in some branch and a PR was pending, correct? If so, point me to the PR or request one, if you have not already done so.

**Comment by Matskuu** [comment]
> @Matskuu I believe you had implemented this in some branch and a PR was pending, correct? If so, point me to the PR or request one, if you have not already done so.

I was referring to the payoff table method. I believe the reference point method was implemented in the old desdeo but not in desdeo2 yet. It might have a UI in desdeo2 also?

**Comment by gialmisi** [comment]
> > @Matskuu I believe you had implemented this in some branch and a PR was pending, correct? If so, point me to the PR or request one, if you have not already done so.
> 
> I was referring to the payoff table method. I believe the reference point method was implemented in the old desdeo but not in desdeo2 yet. It might have a UI in desdeo2 also?

Ahh, yes. I remember now. Thanks for the clarification. In that case, the reference method needs still to be implemented. Not by you right now necessarely.

**Comment by gialmisi** [comment]
Addressed in commit a844bfd closing.
